name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  # CI Pipeline
  build:
    name: CI Pipeline
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      # Install Node.js dependencies
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: pnpm install

      # Build Typescript
      - name: Run build
        working-directory: ${{ env.working-directory }}
        run: pnpm run build

  # CD Pipeline
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['16.x']
    needs: build
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Create .env file
      - name: Create .env file
        working-directory: ${{ env.env-directory }}
        run: |
          touch .env
          echo PORT=8080 >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URL }} >> .env
          cat .env

      # Install Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      # Install Node.js dependencies
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: pnpm install

      # Build Typescript
      - name: Run build
        working-directory: ${{ env.working-directory }}
        run: pnpm run build

      # Install AWS CLI 2
      - name: Install AWS CLI 2
        working-directory: ${{ env.working-directory }}
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          which aws
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Make to ZIP file with source code
      # -x 명령어 뒤에 해당하는 파일은 zip 파일 생성 시 제외
      - name: Generate deployment Beanstalk
        working-directory: ${{ env.working-directory }}
        run: zip -r deploy.zip . -x '*.git*' './src/*' './aws/*' awscliv2.zip

      # Get Current Time
      - name: Get Current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH-mm-ss
          utcOffset: '+09:00'

      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          region: ${{ secrets.AWS_REGION }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          version_label: ${{ steps.current-time.outputs.formattedTime }}
          deployment_package: ./deploy.zip
          wait_for_environment_recovery: 300
